# Generated by Django 4.0.5 on 2022-06-04 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_card', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('price', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='image/')),
            ],
        ),
    ]
